### ISSUE TITLE
Location in context menu

### ISSUE THREAD

**Issue by br4nnigan** [brettz9/copylinktext#14]
The screenshot on the addons page shows the function right under "copy link location" which is where I'd prefer it. 

However it's somewhere completely different for me. Is it possible to change that?

![](https://i.imgur.com/CXCyRnC.jpg)

**Comment by brettz9** [comment]
Sorry just seeing this now... Unfortunately, with the WebExtensions system as it is now, this is not under our control... Firefox has massively limited what can be done with add-ons... Feel free to reopen if any changes in the API allow for control of placement, but I wouldn't hold my breath...

**Comment by br4nnigan** [comment]
thanks Mozilla (ironically)

thanks brettz (unironically)

personally I'm using Waterfox so I can continue using the "bad" old addons.
