### ISSUE TITLE
Now working on my laptop

### ISSUE THREAD

**Issue by franklinyu** [brettz9/copylinktext#4]
Firefox version: 35.0.1
Windows version: 8.1
copy link text version: 1.7.1

Not showing up at right-click context menu. Tried reinstall the add-on and restarted Firefox. Tried disable all the other add-ons. Any possible reason or further test?

**Comment by brettz9** [comment]
Do you have a sample page and link you are trying with it? Can you go to Tools->Web Developer->Browser Console and tell me if there are any errors you are seeing there? I have the exact same configuration as you and am not having any problems. Did you install from the Addons site or from the repository?

**Comment by franklinyu** [comment]
I am trying it everywhere, including google. I can find the “Browser Console”, but there are a lot of stuffs; shall I bring all of them to you?

**Comment by brettz9** [comment]
You might try searching for "copylinktext" and if something shows up, you can just copy that alone; otherwise, yes, you can send it all...

Where did you install the add-on from?

**Comment by brettz9** [comment]
If you are concerned about privacy, you can email me at brettz9@yahoo.com

**Comment by brettz9** [comment]
Do you have a menu editing add-on installed?

**Comment by brettz9** [comment]
I'm going to close this issue, as I have not heard back from you, though you can continue to comment. FYI, if you were talking about private browsing, I've just uploaded a version which will work with private browser windows.
