### ISSUE TITLE
[minor] JS console warning

### ISSUE THREAD

**Issue by atomGit** [brettz9/copylinktext#5]
1) JavaScript 1.7's let blocks are deprecated -- clipboard.js:129:6

2) TypeError: messageManager is undefined context-menu.js:690:2
the above points to this:
  messageManager.sendAsyncMessage("sdk/contextmenu/createitems", {

add-on works, just bringing this to dev's attention

**Comment by brettz9** [comment]
Thank you very much for the report, but as it happens, in both of these cases, the messages are coming from files which are supplied by Firefox's own SDK. Feel free to comment further, but I will close the issue now.

**Comment by brettz9** [comment]
You could report this to Mozilla if you wanted...
