### ISSUE TITLE
Highlight after right-clicking link until selecting a new link or page refresh

### ISSUE THREAD

**Issue by CpcBob** [brettz9/copylinktext#9]
Could you add a feature that when "Copy Link Text" is used it highlights that link.
If another link is copied then the previous highlighted link is removed and the one just copied is highlighted
Reason: a visual of what link was last copied..
Thanks

**Comment by brettz9** [comment]
Hmm... For how long do you wish the highlighting to stay on the link? Only until page refresh or after some time delay?

Out of curiosity, why do you want to see what link was last copied?

**Comment by CpcBob** [comment]
How long to stay highlighted>  Just until page refresh or next link is copied.
When making a hyperlink I use both the Link text & the link or just the text when email or posting.
On a web page with lots of links its hard to keep track of the last one I copied.

**Comment by brettz9** [comment]
Ok, I think that is reasonable enough to go into this add-on. I've added it to my to-do list, but no promises about if and when I may get to it. Thanks!

**Comment by CpcBob** [comment]
Thanks

**Comment by brettz9** [comment]
I've implemented the feature in version `1.9.0` (need to wait for AMO to approve). Note that if you highlight something and then disable the highlighting, you will not be unable to de-highlight the old copy until a page refresh. Thanks for the suggestion!
